export const CHARACTER_OPTIONS = [
  {
    id: "male_reception",
    label: "Cán bộ Một Cửa (Nam)",
    gender: "male",
    genderLabel: "Nam",
    title: "Tiếp Nhận Hồ Sơ",
    icon: "📋",
    color: "#0284c7",
    accentColor: "#38bdf8",
    hairColor: "#331800",
    hairStyle: "side_part",
    outfit: "shirt_tie",
    description: "Cán bộ trẻ năng động, tận tụy hỗ trợ nhân dân tại bộ phận một cửa.",
  },
  {
    id: "female_dialogue",
    label: "Cán bộ Tiếp Dân (Nữ)",
    gender: "female",
    genderLabel: "Nữ",
    title: "Lắng Nghe Nhân Dân",
    icon: "🏡",
    color: "#db2777",
    accentColor: "#f472b6",
    hairColor: "#1c1917",
    hairStyle: "ponytail",
    outfit: "blouse_ribbon",
    description: "Nữ cán bộ ân cần, luôn thấu hiểu và giải quyết thấu đáo tâm tư người dân.",
  },
  {
    id: "male_digital",
    label: "Chuyên viên Số Hóa (Nam)",
    gender: "male",
    genderLabel: "Nam",
    title: "Dữ Liệu & Công Nghệ",
    icon: "💻",
    color: "#059669",
    accentColor: "#34d399",
    hairColor: "#1e293b",
    hairStyle: "short_taper",
    outfit: "tech_vest",
    description: "Chuyên viên công nghệ số, chuẩn hóa quy trình và minh bạch thông tin.",
  },
  {
    id: "female_inspector",
    label: "Cán bộ Thanh Tra (Nữ)",
    gender: "female",
    genderLabel: "Nữ",
    title: "Kiểm Soát Liêm Chính",
    icon: "⚖️",
    color: "#d97706",
    accentColor: "#fbbf24",
    hairColor: "#451a03",
    hairStyle: "bob_clip",
    outfit: "inspector_suit",
    description: "Nữ thanh tra công tâm, chính trực, bảo vệ kỷ cương và liêm chính công vụ.",
  },
  {
    id: "male_approval",
    label: "Cán bộ Thẩm Định (Nam)",
    gender: "male",
    genderLabel: "Nam",
    title: "Phê Duyệt & Niêm Phong",
    icon: "🏛️",
    color: "#b91c1c",
    accentColor: "#f87171",
    hairColor: "#0f172a",
    hairStyle: "neat_pompadour",
    outfit: "formal_suit",
    description: "Cán bộ thẩm định dày dạn, thận trọng và chuẩn xác trong từng văn bản.",
  },
  {
    id: "female_youth",
    label: "Đoàn Viên Xung Kích (Nữ)",
    gender: "female",
    genderLabel: "Nữ",
    title: "Thế Hệ Trẻ Tiên Phong",
    icon: "⭐",
    color: "#8b5cf6",
    accentColor: "#c084fc",
    hairColor: "#291508",
    hairStyle: "long_twin",
    outfit: "youth_jacket",
    description: "Đại diện thế hệ trẻ xung kích, đi đầu trong đổi mới và vì dân phục vụ.",
  },
];

export const getCharacterOption = (id) => {
  return CHARACTER_OPTIONS.find((character) => character.id === id) || CHARACTER_OPTIONS[0];
};
