// Database of Interactive Dialogues - Chương 5: Cơ cấu xã hội - giai cấp trong thời kỳ quá độ lên CNXH

export const HISTORICAL_NPCS_BY_PHASE = {
  phase_1: [
    {
      id: "npc_p1_theorist",
      name: "GS. Nguyễn Văn An",
      roleTitle: "Nhà Lý Luận Xã Hội Học Mác - Lênin",
      avatarColor: "#0284c7",
      avatarGender: "male",
      icon: "📚",
      x: 520,
      y: 380,
      quote: "Trong CNXHKH, cơ cấu xã hội - giai cấp là chìa khóa mở ra bản chất của mọi mối quan hệ xã hội!",
      context: "Chương 5 Giáo trình CNXHKH nghiên cứu về các loại hình cơ cấu xã hội (dân cư, nghề nghiệp, giai cấp, dân tộc, tôn giáo) và đặt trọng tâm vào cơ cấu xã hội - giai cấp.",
      question: "Vì sao trong môn Chủ nghĩa xã hội khoa học, cơ cấu xã hội - giai cấp lại được tập trung nghiên cứu hàng đầu trong số các loại hình cơ cấu xã hội?",
      options: [
        {
          id: "opt_p1_q1_wrong1",
          text: "Vì đây là loại hình cơ cấu xã hội duy nhất tồn tại và vận động trong thời kỳ quá độ lên chủ nghĩa xã hội.",
          isCorrect: false,
          badge: "HIỂU SAI THỰC TẾ",
          feedbackTitle: "❌ Không Phải Là Loại Hình Duy Nhất!",
          feedbackExplanation: "Trong thời kỳ quá độ tồn tại đồng thời nhiều loại hình cơ cấu xã hội như: cơ cấu dân cư, nghề nghiệp, dân tộc, tôn giáo... chứ không chỉ duy nhất có cơ cấu giai cấp.",
          scoreDelta: 0,
        },
        {
          id: "opt_p1_q1_correct",
          text: "Vì nó liên quan trực tiếp đến vấn đề giai cấp, lợi ích kinh tế - chính trị và liên minh giữa các giai tầng trong chế độ xã hội.",
          isCorrect: true,
          badge: "BẢN CHẤT LÝ LUẬN",
          feedbackTitle: "⭐ Nhận Thức Lý Luận Hoàn Toàn Chính Xác!",
          feedbackExplanation: "Cơ cấu xã hội - giai cấp gắn liền với sở hữu tư liệu sản xuất và quyền lực nhà nước, quyết định bản chất kinh tế - chính trị của xã hội và là cơ sở để xây dựng khối liên minh giai cấp!",
          scoreDelta: 10,
        },
        {
          id: "opt_p1_q1_wrong2",
          text: "Vì các cơ cấu dân cư, nghề nghiệp, tôn giáo hoàn toàn không có bất kỳ vai trò hay tác động gì đến sự phát triển đất nước.",
          isCorrect: false,
          badge: "XEM NHẸ CÁC CƠ CẤU KHÁC",
          feedbackTitle: "❌ Tuyệt Đối Hóa Sai Lầm!",
          feedbackExplanation: "Mỗi loại hình cơ cấu xã hội đều có vị trí, vai trò riêng và tác động qua lại chặt chẽ với nhau. Không được xem nhẹ các cơ cấu dân cư, nghề nghiệp, dân tộc hay tôn giáo.",
          scoreDelta: 0,
        },
      ],
    },
    {
      id: "npc_p1_statistician",
      name: "Chuyên Viên Thống Kê Xã Hội",
      roleTitle: "Viện Nghiên Cứu Xã Hội Học Ứng Dụng",
      avatarColor: "#15803d",
      avatarGender: "male",
      icon: "📊",
      x: 1400,
      y: 380,
      quote: "Muốn hiểu cấu trúc xã hội, phải nắm chắc 4 quan hệ nền tảng giữa các giai cấp, tầng lớp!",
      context: "Khái niệm cơ cấu xã hội - giai cấp chỉ hệ thống các giai cấp, tầng lớp tồn tại khách quan và các mối quan hệ xã hội giữa chúng.",
      question: "Theo định nghĩa chuẩn mực, cơ cấu xã hội - giai cấp phản ánh các mối quan hệ giữa các giai cấp, tầng lớp trên những phương diện cốt lõi nào?",
      options: [
        {
          id: "opt_p1_q2_wrong1",
          text: "Chỉ đơn thuần phản ánh tuổi tác, giới tính, nơi cư trú và thói quen sinh hoạt hàng ngày của người dân.",
          isCorrect: false,
          badge: "NHẦM LẪN DÂN CƯ",
          feedbackTitle: "❌ Đây Là Tiêu Chí Cơ Cấu Dân Cư!",
          feedbackExplanation: "Tuổi tác, giới tính và nơi cư trú thuộc về cơ cấu xã hội - dân cư hoặc nhân khẩu học, không phản ánh bản chất giai cấp.",
          scoreDelta: 0,
        },
        {
          id: "opt_p1_q2_wrong2",
          text: "Chỉ phản ánh trình độ ngoại ngữ và sở thích giải trí của các nhóm thanh niên trong xã hội hiện đại.",
          isCorrect: false,
          badge: "LỆCH LẠC NỘI DUNG",
          feedbackTitle: "❌ Không Phản Ánh Quan Hệ Sản Xuất!",
          feedbackExplanation: "Sở thích và ngoại ngữ là tiêu chí thị hiếu/văn hóa cá nhân, không cấu thành bản chất kinh tế - chính trị của cơ cấu xã hội - giai cấp.",
          scoreDelta: 0,
        },
        {
          id: "opt_p1_q2_correct",
          text: "Về sở hữu tư liệu sản xuất, tổ chức quản lý sản xuất, địa vị chính trị - xã hội và phân phối lợi ích.",
          isCorrect: true,
          badge: "4 QUAN HỆ CỐT LÕI",
          feedbackTitle: "🎯 Chính Xác 4 Quan Hệ Nền Tảng!",
          feedbackExplanation: "Chính 4 phương diện này (sở hữu TLSX, quản lý, địa vị chính trị, phân phối lợi ích) xác định vị trí và vai trò khách quan của mỗi giai cấp, tầng lớp trong đời sống xã hội!",
          scoreDelta: 10,
        },
      ],
    },
  ],

  phase_2: [
    {
      id: "npc_p2_moderator",
      name: "Chuyên Viên Ban Dân Tộc - Tôn Giáo TW",
      roleTitle: "Chuyên Viên Chính Sách Đại Đoàn Kết",
      avatarColor: "#b91c1c",
      avatarGender: "male",
      icon: "🤝",
      x: 520,
      y: 380,
      quote: "Khi cơ cấu giai cấp biến đổi, cơ cấu nghề nghiệp, dân cư, dân tộc, tôn giáo cũng chuyển động theo!",
      context: "Nghiên cứu về vị trí của cơ cấu xã hội - giai cấp: cơ cấu này giữ vị trí quan trọng hàng đầu và có tác động sâu sắc đến các loại hình cơ cấu xã hội khác.",
      question: "Quy luật tác động qua lại giữa cơ cấu xã hội - giai cấp và các loại hình cơ cấu xã hội khác được biểu hiện như thế nào?",
      options: [
        {
          id: "opt_p2_q1_wrong1",
          text: "Cơ cấu giai cấp và các cơ cấu khác hoàn toàn biệt lập, không hề có bất kỳ sự liên hệ hay ảnh hưởng nào lẫn nhau.",
          isCorrect: false,
          badge: "SIÊU HÌNH TÁCH RỜI",
          feedbackTitle: "❌ Quan Điểm Siêu Hình Tách Rời!",
          feedbackExplanation: "Các loại hình cơ cấu xã hội luôn nằm trong một chỉnh thể thống nhất hữu cơ và tác động qua lại mật thiết với nhau.",
          scoreDelta: 0,
        },
        {
          id: "opt_p2_q1_correct",
          text: "Khi vị trí, số lượng, vai trò và lợi ích của các giai cấp thay đổi thì cơ cấu nghề nghiệp, dân cư, dân tộc, tôn giáo cũng biến đổi theo.",
          isCorrect: true,
          badge: "TÁC ĐỘNG LAN TỎA",
          feedbackTitle: "⭐ Nắm Rất Vững Tính Lan Tỏa Xã Hội!",
          feedbackExplanation: "Cơ cấu xã hội - giai cấp giữ vị trí trung tâm, định hình và chi phối xu hướng biến đổi của cơ cấu nghề nghiệp, phân bố dân cư, quan hệ dân tộc và tôn giáo!",
          scoreDelta: 10,
        },
        {
          id: "opt_p2_q1_wrong2",
          text: "Cơ cấu giai cấp luôn lập tức xóa bỏ hoàn toàn mọi bản sắc văn hóa dân tộc và tín ngưỡng tôn giáo.",
          isCorrect: false,
          badge: "CỰC ĐOAN GIÁO ĐIỀU",
          feedbackTitle: "❌ Hiểu Sai Chủ Trương Xã Hội Chủ Nghĩa!",
          feedbackExplanation: "Chủ nghĩa xã hội tôn trọng quyền bình đẳng dân tộc, tự do tín ngưỡng tôn giáo chứ không xóa bỏ bản sắc văn hóa dân tộc.",
          scoreDelta: 0,
        },
      ],
    },
    {
      id: "npc_p2_theorist_note",
      name: "Chuyên Gia Phương Pháp Luận",
      roleTitle: "Hội Đồng Lý Luận Trung Ương",
      avatarColor: "#d97706",
      avatarGender: "male",
      icon: "⚖️",
      x: 1400,
      y: 380,
      quote: "Lưu ý sống còn: Tôn trọng vị trí hàng đầu nhưng tuyệt đối không được tuyệt đối hóa vai trò giai cấp!",
      context: "Giáo trình nhấn mạnh lưu ý phương pháp luận quan trọng: Không được tuyệt đối hóa vai trò của CCXH-GC và xem nhẹ các loại hình cơ cấu xã hội khác.",
      question: "Nếu một người quản lý 'tuyệt đối hóa vai trò của cơ cấu xã hội - giai cấp và xem nhẹ các cơ cấu khác' thì sẽ dẫn đến sai lầm nguy hại nào?",
      options: [
        {
          id: "opt_p2_q2_wrong1",
          text: "Sẽ giúp xã hội phát triển nhanh chóng và xóa bỏ hoàn toàn mọi mâu thuẫn xã hội trong thời gian ngắn.",
          isCorrect: false,
          badge: "ẢO TƯỞNG DUY TÂM",
          feedbackTitle: "❌ Ảo Tưởng Nóng Vội Duy Tâm!",
          feedbackExplanation: "Giáo điều và cực đoan giai cấp chỉ gây thêm mâu thuẫn và kìm hãm phát triển kinh tế - xã hội.",
          scoreDelta: 0,
        },
        {
          id: "opt_p2_q2_wrong2",
          text: "Không gây ra bất kỳ tác hại nào vì cơ cấu giai cấp là yếu tố duy nhất quyết định xã hội.",
          isCorrect: false,
          badge: "PHỦ NHẬN LƯU Ý",
          feedbackTitle: "❌ Trái Với Cảnh Báo Của Giáo Trình!",
          feedbackExplanation: "Giáo trình CNXHKH đặc biệt cảnh báo bài học này để tránh những sai lầm tả khuynh, nóng vội trong lịch sử.",
          scoreDelta: 0,
        },
        {
          id: "opt_p2_q2_correct",
          text: "Dễ rơi vào chủ quan, giáo điều, làm tổn hại khối đại đoàn kết toàn dân tộc và xem nhẹ tính đặc thù của dân tộc, tôn giáo.",
          isCorrect: true,
          badge: "PHƯƠNG PHÁP LUẬN BIỆN CHỨNG",
          feedbackTitle: "⚖️ Nhận Thức Biện Chứng Chuẩn Xác!",
          feedbackExplanation: "Tuyệt đối hóa yếu tố giai cấp một chiều sẽ bóp méo thực tiễn xã hội, chia rẽ khối đại đoàn kết dân tộc và gây căng thẳng không đáng có trong quản lý!",
          scoreDelta: 10,
        },
      ],
    },
  ],

  phase_3: [
    {
      id: "npc_p3_union_leader",
      name: "Đại Biểu Công Đoàn CNH Hiện Đại",
      roleTitle: "Lực Lượng Tiên Phong Công Nhân Hiện Đại",
      avatarColor: "#0284c7",
      avatarGender: "male",
      icon: "⚙️",
      x: 520,
      y: 380,
      quote: "Kinh tế biến đổi ➔ Lao động nghề nghiệp biến đổi ➔ Cơ cấu giai cấp biến đổi: Đó là quy luật khách quan!",
      context: "Xu hướng 1 về quy luật biến đổi: Cơ cấu xã hội - giai cấp biến đổi gắn liền và bị quy định bởi cơ cấu kinh tế.",
      question: "Mạch vận động có tính quy luật của cơ cấu xã hội - giai cấp trong quá trình công nghiệp hóa, hiện đại hóa diễn ra như thế nào?",
      options: [
        {
          id: "opt_p3_q1_wrong1",
          text: "Cơ cấu giai cấp tự biến đổi ngẫu nhiên theo thời gian mà hoàn toàn không phụ thuộc vào cơ sở kinh tế hay lực lượng sản xuất.",
          isCorrect: false,
          badge: "PHỦ NHẬN KINH TẾ",
          feedbackTitle: "❌ Trái Ngược Chủ Nghĩa Duy Vật Lịch Sử!",
          feedbackExplanation: "Theo chủ nghĩa duy vật lịch sử, tồn tại xã hội và cơ sở kinh tế luôn quyết định ý thức xã hội và kết cấu giai tầng.",
          scoreDelta: 0,
        },
        {
          id: "opt_p3_q1_correct",
          text: "Cơ cấu kinh tế đổi ➔ Cơ cấu lao động & nghề nghiệp đổi ➔ Vị trí, vai trò giai cấp đổi ➔ CCXH-GC biến đổi; nông nghiệp giảm tỷ trọng, công nghiệp và dịch vụ tăng.",
          isCorrect: true,
          badge: "QUY LUẬT KHÁCH QUAN",
          feedbackTitle: "⚙️ Nắm Vững Sợi Chỉ Đỏ Của Quy Luật!",
          feedbackExplanation: "Chính cơ cấu kinh tế nhiều thành phần và CNH-HĐH quyết định sự chuyển dịch cơ cấu lao động, thúc đẩy đội ngũ công nhân, trí thức và doanh nhân phát triển mạnh mẽ!",
          scoreDelta: 10,
        },
        {
          id: "opt_p3_q1_wrong2",
          text: "Tỷ trọng lao động nông nghiệp tăng vọt lên 95%, trong khi ngành công nghiệp và dịch vụ hoàn toàn biến mất.",
          isCorrect: false,
          badge: "LỆCH LẠC XU HƯỚNG",
          feedbackTitle: "❌ Ngược Với Xu Hướng CNH - HĐH!",
          feedbackExplanation: "Xu hướng quy luật trong CNH-HĐH là giảm tỷ trọng lao động nông nghiệp, tăng tỷ trọng công nghiệp và kinh tế dịch vụ.",
          scoreDelta: 0,
        },
      ],
    },
    {
      id: "npc_p3_innovator",
      name: "TS. Lê Thị Mai Lan",
      roleTitle: "Chuyên Gia Đổi Mới & Kinh Tế Tri Thức",
      avatarColor: "#7c3aed",
      avatarGender: "female",
      icon: "💡",
      x: 1400,
      y: 380,
      quote: "Quan hệ giai tầng vừa đấu tranh vừa liên minh, từng bước thu hẹp khoảng cách để xích lại gần nhau!",
      context: "Xu hướng 2 và 3: Xuất hiện các tầng lớp mới (doanh nhân, trí thức số), đồng thời các giai tầng vận động trong mối quan hệ vừa đấu tranh vừa liên minh.",
      question: "Mục tiêu và xu hướng phát triển tiến bộ trong mối quan hệ giữa các giai cấp, tầng lớp ở thời kỳ quá độ lên CNXH là gì?",
      options: [
        {
          id: "opt_p3_q2_wrong1",
          text: "Duy trì sự phân hóa giàu nghèo cùng cực và khoét sâu mâu thuẫn đối kháng bạo lực giữa các tầng lớp trong xã hội.",
          isCorrect: false,
          badge: "ĐỐI KHÁNG TIÊU CỰC",
          feedbackTitle: "❌ Không Phải Bản Chất Xã Hội Chủ Nghĩa!",
          feedbackExplanation: "Mục tiêu của CNXH là dân giàu, nước mạnh, dân chủ, công bằng, văn minh, chứ không phải kích động chia rẽ phân hóa cực đoan.",
          scoreDelta: 0,
        },
        {
          id: "opt_p3_q2_wrong2",
          text: "Cấm đoán và triệt tiêu toàn bộ đội ngũ doanh nhân và những người lao động sáng tạo trong nền kinh tế thị trường.",
          isCorrect: false,
          badge: "KÌM HÃM ĐỔI MỚI",
          feedbackTitle: "❌ Đi Ngược Chủ Trương Của Đảng!",
          feedbackExplanation: "Đội ngũ doanh nhân và trí thức là những lực lượng quan trọng được Đảng và Nhà nước khuyến khích, tạo điều kiện phát triển mạnh mẽ.",
          scoreDelta: 0,
        },
        {
          id: "opt_p3_q2_correct",
          text: "Từng bước thu hẹp những khác biệt bất hợp lý (giữa các giai tầng, thành thị - nông thôn, lao động trí óc - chân tay) để xích lại gần nhau trong liên minh công - nông - trí thức.",
          isCorrect: true,
          badge: "XÍCH LẠI GẦN NHAU",
          feedbackTitle: "🌟 Xu Hướng Tiến Bộ Đầy Nhân Văn!",
          feedbackExplanation: "Xã hội XHCN không duy trì đối kháng giai cấp mà từng bước thu hẹp bất bình đẳng, phát huy liên minh Công - Nông - Trí thức dưới sự lãnh đạo của Đảng để cùng xây dựng đất nước phồn vinh!",
          scoreDelta: 10,
        },
      ],
    },
  ],

  // Fallback alias for safety
  phase_4: []
};
