// Database of Historical NPCs and Interactive HCM202 Dilemma Dialogues (1978–1981)

export const HISTORICAL_NPCS_BY_PHASE = {
  phase_1: [
    {
      id: "npc_p1_farmer",
      name: "Bác Hai Lúa (Xã Viên HTX Đoàn Xá)",
      roleTitle: "Nông Dân Tiên Phong Hải Phòng 1978",
      avatarColor: "#ca8a04",
      avatarGender: "male",
      icon: "👨‍🌾",
      x: 520,
      y: 380,
      quote: "Làm chung chia đều thì 'cha chung không ai khóc', lúa chết khô ngoài đồng!",
      context: "HTX Nông nghiệp Đoàn Xá (Kiến Thụy, Hải Phòng) năm 1978 đang đối mặt với hạn hán, sâu bệnh và nạn thiếu đói. Nông dân không mặn mà với công điểm cào bằng.",
      question: "Theo Cán bộ, HTX chúng ta phải giải quyết thế nào để bà con xã viên hăng hái ra đồng cứu lúa?",
      options: [
        {
          id: "opt_tang_ky_luat",
          text: "Tăng cường kiểm tra kỷ luật, thúc giục xã viên ra đồng tập trung theo tiếng kẻng của HTX.",
          isCorrect: false,
          badge: "CƠ CHẾ QUAN LIÊU",
          feedbackTitle: "❌ Cơ Chế Cũ Không Tạo Động Lực Sản Xuất!",
          feedbackExplanation: "Cơ chế quản lý mệnh lệnh hành chính và phân phối bình quân không kích thích được tính chủ động của người lao động. Khi người nông dân không được hưởng thành quả lao động tương xứng, sản xuất sẽ tiếp tục đình trệ.",
          scoreDelta: 0,
        },
        {
          id: "opt_khoan_chui",
          text: "Giao khoán ruộng và sản phẩm đến từng hộ nông dân (Được giữ lại toàn bộ phần vượt khoán).",
          isCorrect: true,
          badge: "ĐỘT PHÁ THỰC TIỄN",
          feedbackTitle: "🌾 Sáng Kiến 'Khoán Chui' Thành Công Rực Rỡ!",
          feedbackExplanation: "Chính sách khoán sản phẩm đến người lao động gắn chặt lợi ích của người nông dân với ruộng đồng. Năng suất tăng vọt, giải quyết dứt điểm nạn đói tại địa phương và trở thành tiền đề thực tiễn then chốt để Ban Bí thư ban hành Chỉ thị 100-CT/TW (01/1981)!",
          scoreDelta: 10,
        },
        {
          id: "opt_cho_tro_cap",
          text: "Ngồi chờ Nhà nước cấp phát thêm lương thực cứu trợ và máy móc nông nghiệp từ Trung ương.",
          isCorrect: false,
          badge: "THỤ ĐỘNG Ỷ LẠI",
          feedbackTitle: "❌ Ỷ Lại Không Thể Tự Cứu Mình!",
          feedbackExplanation: "Trong bối cảnh viện trợ cắt giảm và ngân sách nhà nước khó khăn, việc thụ động chờ đợi trợ cấp sẽ đẩy xã viên vào nạn đói nghiêm trọng hơn.",
          scoreDelta: 0,
        },
      ],
    },
    {
      id: "npc_p1_secretary",
      name: "Đồng chí Đoàn Duy Thành",
      roleTitle: "Bí Thư Thành Ủy Hải Phòng 1978–1980",
      avatarColor: "#15803d",
      avatarGender: "male",
      icon: "👨‍💼",
      x: 1400,
      y: 380,
      quote: "Thực tiễn là tiêu chuẩn của chân lý. Dân no ấm thì ta phải kiên quyết bảo vệ!",
      context: "Nhiều ý kiến bảo thủ lúc bấy giờ chỉ trích mô hình khoán hộ ở Đoàn Xá là 'chạy theo tư bản', 'phá vỡ quan hệ sản xuất XHCN'. Bí thư Thành ủy đang đứng trước áp lực kỷ luật nặng nề.",
      question: "Đồng chí báo cáo quan điểm với Thành ủy và Trung ương thế nào để bảo vệ mô hình khoán mới?",
      options: [
        {
          id: "opt_bao_ve_khoan",
          text: "Khẳng định: Thực tiễn chứng minh dân no, thóc đầy kho là đúng quy luật; kiên quyết nhân rộng ra toàn thành phố!",
          isCorrect: true,
          badge: "BẢN LĨNH ĐỔI MỚI",
          feedbackTitle: "⭐ Bản Lĩnh Xuất Phát Từ Thực Tiễn!",
          feedbackExplanation: "Sự kiên định và dám chịu trách nhiệm của lãnh đạo Hải Phòng đã bảo vệ được mầm mống đổi mới nông nghiệp, mở đường cho bước đột phá tư duy kinh tế của Đảng!",
          scoreDelta: 10,
        },
        {
          id: "opt_dung_lai_cho_chi_dao",
          text: "Tạm dừng mô hình khoán hộ để làm kiểm điểm và chờ hướng dẫn chính thức từ cấp trên.",
          isCorrect: false,
          badge: "THỤ ĐỘNG CHỜ ĐỢI",
          feedbackTitle: "❌ Bỏ Lỡ Cơ Hội Tháo Gỡ Khủng Hoảng!",
          feedbackExplanation: "Nếu dừng lại vì giáo điều rập khuôn, hàng triệu nông dân sẽ tiếp tục chịu đói và không có bài học thực tiễn để Trung ương xem xét điều chỉnh đường lối.",
          scoreDelta: 0,
        },
        {
          id: "opt_do_loi_cap_duoi",
          text: "Quy toàn bộ trách nhiệm 'khoán chui' cho cấp xã và huyện Kiến Thụy để tránh kỷ luật.",
          isCorrect: false,
          badge: "THIẾU TRÁCH NHIỆM",
          feedbackTitle: "❌ Thiếu Bản Lĩnh Người Lãnh Đạo!",
          feedbackExplanation: "Người lãnh đạo cách mạng cần đứng mũi chịu sào, bảo vệ những sáng kiến đúng đắn vì lợi ích nhân dân thay vì đùn đẩy trách nhiệm cho cấp dưới.",
          scoreDelta: 0,
        },
      ],
    },
  ],

  phase_2: [
    {
      id: "npc_p2_ba_thi",
      name: "Bà Ba Thi (Nguyễn Thị Ráo)",
      roleTitle: "Giám Đốc Công Ty Lương Thực TP.HCM 1979",
      avatarColor: "#db2777",
      avatarGender: "female",
      icon: "👩‍💼",
      x: 520,
      y: 380,
      quote: "Nếu đi tù mà cứu được dân thành phố không bị đói, tôi xin chịu một mình!",
      context: "Năm 1979, TP.HCM thiếu lương thực trầm trọng, khẩu phần gạo giảm sút nguy cấp. Cơ chế giá thu mua nhà nước quá thấp khiến nông dân miền Tây không bán lúa cho nhà nước.",
      question: "Trước nguy cơ dân thành phố đứt bữa, Bà Ba Thi đã đưa ra quyết định đột phá nào?",
      options: [
        {
          id: "opt_cat_giam_dinh_luong",
          text: "Tiếp tục cắt giảm định lượng gạo tem phiếu của người dân và nghiêm cấm giao thương tự do.",
          isCorrect: false,
          badge: "BẾ TẮC QUAN LIÊU",
          feedbackTitle: "❌ Làm Khủng Hoảng Thêm Trầm Trọng!",
          feedbackExplanation: "Cắt giảm khẩu phần trong khi kho dự trữ cạn kiệt chỉ làm đời sống nhân dân kiệt quệ và thị trường chợ đen bùng phát dữ dội hơn.",
          scoreDelta: 0,
        },
        {
          id: "opt_ep_gia_nong_dan",
          text: "Cưỡng chế nông dân miền Tây phải bán toàn bộ lúa gạo theo đúng giá thu mua bao cấp thấp.",
          isCorrect: false,
          badge: "MỆNH LỆNH HÀNH CHÍNH",
          feedbackTitle: "❌ Gây Đứt Gãy Nguồn Cung Lương Thực!",
          feedbackExplanation: "Dùng mệnh lệnh hành chính ép giá sẽ khiến nông dân giấu lúa hoặc bỏ hoang ruộng đất, triệt tiêu động lực sản xuất nông nghiệp.",
          scoreDelta: 0,
        },
        {
          id: "opt_xe_rao_mua_gao",
          text: "'Xé rào' xuống các tỉnh Đồng bằng Sông Cửu Long mua lúa gạo theo giá thỏa thuận thực tế của thị trường.",
          isCorrect: true,
          badge: "MŨI ĐỘT PHÁ LƯƠNG THỰC",
          feedbackTitle: "🌾 Đột Phá 'Cứu Đói' Lịch Sử!",
          feedbackExplanation: "Hành động 'xé rào' dũng cảm của Bà Ba Thi và lãnh đạo TP.HCM (đồng chí Võ Văn Kiệt) đã gom được hàng chục vạn tấn gạo, cứu đói thành phố và chứng minh quy luật giá trị thị trường không thể bị bãi bỏ bằng mệnh lệnh hành chính!",
          scoreDelta: 10,
        },
      ],
    },
    {
      id: "npc_p2_engineer",
      name: "Kỹ Sư Trưởng Xí Nghiệp Dệt",
      roleTitle: "Lực Lượng Công Nhân Dệt Thành Công 1979",
      avatarColor: "#0284c7",
      avatarGender: "male",
      icon: "🏭",
      x: 1400,
      y: 380,
      quote: "Chỉ tiêu Nhà nước chỉ cấp 30% bông sợi, không tự cứu mình thì nhà máy chết!",
      context: "Nhà nước không còn nguồn ngoại tệ để cấp đủ nguyên liệu bông sợi cho xí nghiệp dệt. Hàng ngàn công nhân đối mặt nguy cơ mất việc làm và đình đốn sản xuất.",
      question: "Xí nghiệp Dệt Thành Công đã thực hiện giải pháp gì để 'tự cứu mình và cứu nhà máy'?",
      options: [
        {
          id: "opt_dong_cua_nha_may",
          text: "Đóng cửa bớt dây chuyền máy dệt và chờ Nhà nước phân bổ nguyên liệu theo kế hoạch.",
          isCorrect: false,
          badge: "ĐÌNH ĐỐN THỤ ĐỘNG",
          feedbackTitle: "❌ Triệt Tiêu Tiềm Năng Công Nghiệp!",
          feedbackExplanation: "Thụ động chờ đợi trong bối cảnh nguồn viện trợ bị cắt giảm sẽ làm phá sản các xí nghiệp quốc doanh lớn của đất nước.",
          scoreDelta: 0,
        },
        {
          id: "opt_tu_can_doi_p2",
          text: "Chủ động vay ngoại tệ, nhập khẩu sợi bông và xuất khẩu vải trực tiếp ra thị trường mở (Kế hoạch B/P2).",
          isCorrect: true,
          badge: "TỰ CHỦ CÔNG NGHIỆP",
          feedbackTitle: "🧵 Khơi Nguồn Kế Hoạch 3 Phần!",
          feedbackExplanation: "Mô hình tự cân đối nguyên liệu của Dệt Thành Công và các xí nghiệp TP.HCM đã tạo nên Nghị quyết Trung ương 6 khóa IV (08/1979) 'làm cho sản xuất bung ra' và sau đó là Quyết định 25-CP (01/1981)!",
          scoreDelta: 10,
        },
        {
          id: "opt_chuyen_nghe_khac",
          text: "Thanh lý toàn bộ dàn máy dệt hiện đại để công nhân đi làm nông nghiệp thời vụ.",
          isCorrect: false,
          badge: "PHÁ VỠ NỀN TẢNG",
          feedbackTitle: "❌ Phá Hủy Năng Lực Công Nghiệp Đất Nước!",
          feedbackExplanation: "Tháo dỡ máy móc làm mất đi năng lực công nghiệp cốt lõi, khiến hàng vạn thợ dệt lành nghề mất kế sinh nhai.",
          scoreDelta: 0,
        },
      ],
    },
  ],

  phase_3: [
    {
      id: "npc_p3_chin_can",
      name: "Đồng chí Nguyễn Văn Chính (Chín Cần)",
      roleTitle: "Bí Thư Tỉnh Ủy Long An 1980",
      avatarColor: "#b91c1c",
      avatarGender: "male",
      icon: "🏛️",
      x: 520,
      y: 380,
      quote: "Phải dũng cảm bãi bỏ ngăn sông cấm chợ và bù giá vào lương để cứu nền kinh tế!",
      context: "Năm 1980, Tỉnh Long An tiên phong quyết định bãi bỏ các trạm kiểm soát nội địa ('ngăn sông cấm chợ') và thực hiện thí điểm cơ chế 'Bù giá vào lương'.",
      question: "Ý nghĩa lý luận và thực tiễn cốt lõi của bước đột phá 'Bù giá vào lương' ở Long An là gì?",
      options: [
        {
          id: "opt_bu_gia_vao_luong",
          text: "Xóa bỏ cơ chế bao cấp hiện vật qua tem phiếu, đưa tiền lương và giá cả gắn với quy luật giá trị thực tế.",
          isCorrect: true,
          badge: "ĐỘT PHÁ GIÁ - LƯƠNG - TIỀN",
          feedbackTitle: "📋 Ngọn Cờ Đầu Đổi Mới Phân Phối Lưu Thông!",
          feedbackExplanation: "Mô hình Long An đã chứng minh: Tiền lương phải đủ mua hàng hóa theo giá thực tế, không thể dùng tem phiếu giả tạo để duy trì bao cấp. Mô hình này đã thuyết phục hoàn toàn các đồng chí lãnh đạo Trung ương khi xuống thị sát!",
          scoreDelta: 10,
        },
        {
          id: "opt_siet_chat_tram_gac",
          text: "Lập thêm các trạm gác để kiểm tra chặt chẽ, không cho lúa gạo lọt ra thị trường tự do.",
          isCorrect: false,
          badge: "NGĂN SÔNG CẤM CHỢ",
          feedbackTitle: "❌ Gây Tắc Nghẽn Huyết Mạch Kinh Tế!",
          feedbackExplanation: "Ngăn sông cấm chợ tạo ra tình trạng 'nơi thừa cứ thừa, nơi đói cứ đói', bóp chết sự lưu thông của hàng hóa và gây bất bình trong nhân dân.",
          scoreDelta: 0,
        },
        {
          id: "opt_tang_in_tem_phieu",
          text: "In thêm nhiều loại tem phiếu mới và mở rộng thêm các mặt hàng phân phối định lượng bao cấp.",
          isCorrect: false,
          badge: "LẠM PHÁT BAO CẤP",
          feedbackTitle: "❌ Tem Phiếu Không Thay Thế Được Hàng Hóa!",
          feedbackExplanation: "In thêm tem phiếu mà hàng hóa khan hiếm chỉ khiến tình trạng xếp hàng mua hàng trở nên tồi tệ và chợ đen thao túng giá.",
          scoreDelta: 0,
        },
      ],
    },
    {
      id: "npc_p3_tw_inspector",
      name: "Trưởng Đoàn Khảo Sát Trung Ương",
      roleTitle: "Đoàn Khảo Sát Thị Sát Thực Địa 1980",
      avatarColor: "#d97706",
      avatarGender: "male",
      icon: "📋",
      x: 1400,
      y: 380,
      quote: "Chúng tôi vào tận bến sông, chợ lúa để đối thoại thẳng thắn với nhân dân và cán bộ!",
      context: "Tổng Bí thư Lê Duẩn và các đồng chí lãnh đạo Đảng đã trực tiếp vào thị sát các mô hình Long An, TP.HCM để lắng nghe tiếng nói từ cơ sở.",
      question: "Đoàn Khảo sát Trung ương đã rút ra bài học gì sâu sắc nhất từ những bước 'xé rào' ở miền Nam?",
      options: [
        {
          id: "opt_phe_binh_co_so",
          text: "Phê bình các địa phương vì đã tự ý làm trái quy định tập trung quan liêu bao cấp của Nhà nước.",
          isCorrect: false,
          badge: "BẢO THỦ GIÁO ĐIỀU",
          feedbackTitle: "❌ Dập Tắt Động Lực Phát Triển!",
          feedbackExplanation: "Nếu Đảng bảo thủ phê phán cơ sở thay vì lắng nghe thực tiễn, đất nước sẽ lún sâu vào cuộc khủng hoảng kinh tế - xã hội trầm trọng.",
          scoreDelta: 0,
        },
        {
          id: "opt_giu_nguyen_hien_trang",
          text: "Đánh giá mô hình chỉ là cá biệt tạm bợ và đề nghị duy trì nguyên vẹn cơ chế bao cấp toàn quốc.",
          isCorrect: false,
          badge: "TRÁNH NÉ SỰ THẬT",
          feedbackTitle: "❌ Bỏ Qua Lời Cảnh Báo Của Thực Tiễn!",
          feedbackExplanation: "Thực tiễn đã chỉ ra mô hình cũ không còn phù hợp, nếu né tránh sự thật sẽ dẫn tới đổ vỡ kinh tế vĩ mô kéo dài.",
          scoreDelta: 0,
        },
        {
          id: "opt_thua_nhan_thuc_tien",
          text: "Đảng phải dũng cảm nhìn thẳng vào sự thật, tôn trọng quy luật khách quan và tổng kết thực tiễn để đổi mới đường lối!",
          isCorrect: true,
          badge: "TƯ DUY KHOA HỌC",
          feedbackTitle: "⭐ Bước Chuyển Tư Duy Lịch Sử!",
          feedbackExplanation: "Từ các khảo sát thực tế sinh động này, Tổng Bí thư Lê Duẩn và Trung ương đã đi đến kết luận lịch sử: 'Phải dứt khoát đổi mới cơ chế quản lý kinh tế!'. Đây là nền tảng trực tiếp dẫn tới Chỉ thị 100 và Quyết định 25-CP năm 1981!",
          scoreDelta: 10,
        },
      ],
    },
  ],

  phase_4: [
    {
      id: "npc_p4_theorist",
      name: "Chuyên Gia Nghiên Cứu Kinh Tế TW",
      roleTitle: "Viện Nghiên Cứu Quản Lý Kinh Tế 1981",
      avatarColor: "#7c2d12",
      avatarGender: "male",
      icon: "📚",
      x: 520,
      y: 380,
      quote: "Chỉ thị 100 và Quyết định 25-CP là bước chuyển biến đầu tiên về thể chế hóa!",
      context: "Tháng 1/1981, Ban Bí thư ban hành Chỉ thị 100-CT/TW (Khoán 100) và Chính phủ ban hành Quyết định 25-CP (Kế hoạch 3 phần), chính thức công nhận các sáng kiến từ thực tiễn.",
      question: "Ý nghĩa to lớn nhất của Chỉ thị 100 và Quyết định 25-CP năm 1981 là gì?",
      options: [
        {
          id: "opt_chi_la_tam_thoi",
          text: "Chỉ là chính sách nhượng bộ tạm thời trong lúc khó khăn, sau đó phải siết lại kế hoạch hóa tập trung.",
          isCorrect: false,
          badge: "TƯ DUY LÙI BƯỚC",
          feedbackTitle: "❌ Đánh Giá Sai Quy Luật Phát Triển!",
          feedbackExplanation: "Đây không phải là nhượng bộ tạm thời mà là bước tiến tất yếu của nhận thức lý luận, thừa nhận sản xuất hàng hóa và động lực kinh tế của người lao động.",
          scoreDelta: 0,
        },
        {
          id: "opt_the_che_hoa_3_loi_ich",
          text: "Hợp pháp hóa các mũi đột phá từ cơ sở, kết hợp hài hòa 3 lợi ích: Nhà nước - Tập thể - Người lao động!",
          isCorrect: true,
          badge: "THỂ CHẾ HÓA ĐỔI MỚI",
          feedbackTitle: "📜 Bước Ngoặt Đổi Mới Quản Lý Kinh Tế!",
          feedbackExplanation: "Chỉ thị 100 và Quyết định 25-CP đã cởi trói sức sản xuất, giúp nông nghiệp đạt sản lượng kỷ lục, xí nghiệp công nghiệp hồi phục mạnh mẽ, mở đường thắng lợi cho đường lối Đổi Mới toàn diện tại Đại hội VI (1986)!",
          scoreDelta: 10,
        },
        {
          id: "opt_xoa_bo_toan_bo_nha_nuoc",
          text: "Bãi bỏ hoàn toàn vai trò định hướng của Nhà nước và tư nhân hóa toàn bộ nền kinh tế.",
          isCorrect: false,
          badge: "CHỆCH HƯỚNG",
          feedbackTitle: "❌ Hiểu Sai Mục Tiêu Đổi Mới!",
          feedbackExplanation: "Đổi mới quản lý kinh tế nhằm giải phóng sức sản xuất trong định hướng XHCN, kết hợp hài hòa kế hoạch và thị trường chứ không phải xóa bỏ vai trò chủ đạo của kinh tế nhà nước.",
          scoreDelta: 0,
        },
      ],
    },
    {
      id: "npc_p4_delegate",
      name: "Đại Biểu Hội Nghị Thể Chế 1981",
      roleTitle: "Đại Biểu Các Tỉnh Thành Tham Dự Hội Nghị",
      avatarColor: "#991b1b",
      avatarGender: "male",
      icon: "🏛️",
      x: 1400,
      y: 380,
      quote: "Kế hoạch 3 phần (P1 - P2 - P3) đã cứu sống hàng loạt xí nghiệp công nghiệp!",
      context: "Tại Hội trường 1981, các đại biểu thảo luận sôi nổi về cơ chế tự chủ sản xuất kinh doanh theo Quyết định 25-CP.",
      question: "Cơ chế 'Kế hoạch 3 phần' (P1: Pháp lệnh, P2: Tự cân đối, P3: Phụ gia đình) đã tạo ra động lực mới nào?",
      options: [
        {
          id: "opt_siet_chat_chi_tieu",
          text: "Bắt buộc mọi xí nghiệp chỉ được làm chỉ tiêu P1 do Nhà nước giao, cấm tuyệt đối sản xuất tự cân đối P2 và P3.",
          isCorrect: false,
          badge: "QUẢN LÝ CỨNG NHẮC",
          feedbackTitle: "❌ Bóp Nghẹt Tính Năng Động Xí Nghiệp!",
          feedbackExplanation: "Nếu chỉ duy trì chỉ tiêu cứng P1 mà không có nguyên liệu cấp bù, nhà máy sẽ tiếp tục tê liệt và công nhân không có thu nhập.",
          scoreDelta: 0,
        },
        {
          id: "opt_bo_mac_p1",
          text: "Cho phép doanh nghiệp bỏ bê chỉ tiêu pháp lệnh P1 để dồn toàn bộ nguồn lực làm P3 kiếm lời riêng.",
          isCorrect: false,
          badge: "VI PHẠM KỶ LUẬT",
          feedbackTitle: "❌ Vi Phạm Kỷ Cương Kinh Tế!",
          feedbackExplanation: "Quyết định 25-CP quy định xí nghiệp phải ưu tiên hoàn thành chỉ tiêu pháp lệnh P1 trước khi mở rộng P2 và P3.",
          scoreDelta: 0,
        },
        {
          id: "opt_ke_hoach_3_phan",
          text: "Khuyến khích xí nghiệp chủ động tìm kiếm nguồn nguyên liệu, khai thác thị trường P2 và tăng thu nhập P3 cho công nhân!",
          isCorrect: true,
          badge: "ĐỘNG LỰC SẢN XUẤT",
          feedbackTitle: "⚙️ Giải Phóng Sức Sản Xuất Công Nghiệp!",
          feedbackExplanation: "Nhờ có P2 và P3, các xí nghiệp không còn ỷ lại vào Nhà nước mà chủ động năng động tìm nguyên liệu, mở rộng thị trường, đời sống công nhân được cải thiện rõ rệt!",
          scoreDelta: 10,
        },
      ],
    },
  ],
};
